name: Shell commands

on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout
      - name: run tests
        run: |
          go test -v 
      - name: build
        run: |
          docker build . -t c3ls0/ctm
          
        