name: Shell commands

on: [push]

jobs:
  buildTestAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v1
      - name: docker login 
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}  
      - name: docker build
        run: |
          docker build . -t c3ls0/ctm
      - name: run tests
        run: |
          go test -v          
      - name: docker push
        run: |
          docker push c3ls0/ctm
      - name: deploy in k8s
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        uses: anielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          args: apply -f deployment.yaml      